# Site settings
title: My Awesome Site
description: This is an awesome website.
theme: jekyll-theme-slate

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
  remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
